name: "Policy Build"
description: "Build policy"
author: "Aserto Inc."
branding:
  icon: zap
  color: blue
inputs:
  src:
    description: "directory path to build input source"
    required: true
    default: src
  tag:
    description: "build tag"
    required: true
  revision:
    description: "policy bundle revision"
    required: true
    default: "${GITHUB_SHA}"
  verbosity:
    description: "verbosity level [info|error|debug|trace]"
    required: true
    default: error
runs:
  using: docker
  image: 'docker://ghcr.io/opcr-io/policy:0.0'
  entrypoint: /app/build.sh
